### PR TITLE
Adding audio effect of button_click for more immersive.

### PR DESCRIPTION
**Pull request by bushnerd**
Add audio effect of button_click for more immersive, and my ipad mini 4 is on IOS 12.0.

### CODE REVIEW

**Review by wluc9875 — COMMENTED** [review]
@bushnerd 
Thanks a lot for your contribution! Adding audio effect is a good idea. For more recent iPads, I was thinking of adding a haptic effect.
I don't have the time right now to go through all these differences, but I'll come back to you this weekend about how we can arrange that and then merge your changes.
Could you also tell me where you got the MP3 file from? I need to make sure its license is compatible with iUFCExport license, so that I don't get any issue with Apple or others.
Thanks again!

**Comment by bushnerd** [comment]
Sorry for my missing that, the .mp3 file is M2000 of DCS.

**Comment by jcramb** [comment]
Are you still taking PRs for this project? I'd like to help add an OH-58D keypad but this PR hasn't progressed in over 2 years now...

**Comment by bushnerd** [comment]
Sorry, i will close it

**Pull request closed without merging**
